/*
 * Tugas Besar - Pemrograman Berorientasi Objek
 * Muhammad Maulud H. R. | 1301154166
 * M. Widadio Ilham	  | 1301154360
 * Afra W. D.	  | 1301150432
 */
package viewOld;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Muhammad Maulud H R
 */
public class Authentication extends javax.swing.JFrame {
    
    /**
     * Creates new form Authentication
     */
    public Authentication() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lbl_Username = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        underlineUsername = new javax.swing.JSeparator();
        lbl_Password = new javax.swing.JLabel();
        underlinePassword = new javax.swing.JSeparator();
        btnLogin = new java.awt.Button();
        jPasswordField1 = new javax.swing.JPasswordField();
        panelReg = new javax.swing.JPanel();
        headerSignUp = new javax.swing.JLabel();
        lbl_Nama = new javax.swing.JLabel();
        tfNamaSU = new javax.swing.JTextField();
        lbl_NIM = new javax.swing.JLabel();
        tfNIMSU = new javax.swing.JTextField();
        lbl_TTL = new javax.swing.JLabel();
        tfTempatLahirSU = new javax.swing.JTextField();
        tglHari = new javax.swing.JComboBox<>();
        tglBulan = new javax.swing.JComboBox<>();
        tglTahun = new javax.swing.JComboBox<>();
        lbl_Alamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lbl_UsernameSU = new javax.swing.JLabel();
        tfUsernameSU = new javax.swing.JTextField();
        lbl_PasswordSU = new javax.swing.JLabel();
        tfPasswordSU = new javax.swing.JTextField();
        btnRegister = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        panelLogin.setBackground(new java.awt.Color(51, 204, 255));
        panelLogin.setPreferredSize(new java.awt.Dimension(350, 394));

        lbl_Username.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_Username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Username.setText("Username");

        tfUsername.setBackground(new java.awt.Color(51, 204, 255));
        tfUsername.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setBorder(null);
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        underlineUsername.setForeground(new java.awt.Color(51, 51, 51));

        lbl_Password.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_Password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Password.setText("Password");

        underlinePassword.setForeground(new java.awt.Color(51, 51, 51));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnLogin.setLabel("log-in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(0, 204, 255));
        jPasswordField1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(underlinePassword)
                    .addComponent(underlineUsername)
                    .addComponent(lbl_Password)
                    .addComponent(lbl_Username)
                    .addComponent(tfUsername)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(lbl_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbl_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlinePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        panelReg.setBackground(new java.awt.Color(0, 153, 255));

        headerSignUp.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        headerSignUp.setForeground(new java.awt.Color(255, 255, 255));
        headerSignUp.setText("Sign Up");

        lbl_Nama.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_Nama.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nama.setText("Nama");

        tfNamaSU.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfNamaSU.setForeground(new java.awt.Color(51, 51, 51));
        tfNamaSU.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_NIM.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_NIM.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NIM.setText("NIM");

        tfNIMSU.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfNIMSU.setForeground(new java.awt.Color(51, 51, 51));
        tfNIMSU.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_TTL.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_TTL.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TTL.setText("Tempat, Tanggal Lahir");

        tfTempatLahirSU.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfTempatLahirSU.setForeground(new java.awt.Color(51, 51, 51));
        tfTempatLahirSU.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfTempatLahirSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempatLahirSUActionPerformed(evt);
            }
        });

        tglHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        tglBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        tglTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        lbl_Alamat.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_Alamat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Alamat.setText("Alamat");

        jTextPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPane1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTextPane1);

        lbl_UsernameSU.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_UsernameSU.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UsernameSU.setText("Username");

        tfUsernameSU.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfUsernameSU.setForeground(new java.awt.Color(51, 51, 51));
        tfUsernameSU.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_PasswordSU.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
        lbl_PasswordSU.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PasswordSU.setText("Password");

        tfPasswordSU.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        tfPasswordSU.setForeground(new java.awt.Color(51, 51, 51));
        tfPasswordSU.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegister.setLabel("Register");
        btnRegister.setName(""); // NOI18N

        javax.swing.GroupLayout panelRegLayout = new javax.swing.GroupLayout(panelReg);
        panelReg.setLayout(panelRegLayout);
        panelRegLayout.setHorizontalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerSignUp)
                    .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegLayout.createSequentialGroup()
                            .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Alamat)
                                .addComponent(lbl_TTL)
                                .addComponent(lbl_UsernameSU)
                                .addComponent(lbl_PasswordSU)
                                .addComponent(lbl_Nama)
                                .addComponent(lbl_NIM))
                            .addGap(47, 47, 47)
                            .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNamaSU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRegLayout.createSequentialGroup()
                                        .addComponent(tfTempatLahirSU)
                                        .addGap(18, 18, 18)
                                        .addComponent(tglHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tglBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tglTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUsernameSU, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPasswordSU, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfNIMSU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelRegLayout.setVerticalGroup(
            panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(headerSignUp)
                .addGap(51, 51, 51)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nama)
                    .addComponent(tfNamaSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNIMSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NIM))
                .addGap(18, 18, 18)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TTL)
                    .addComponent(tfTempatLahirSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Alamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UsernameSU)
                    .addComponent(tfUsernameSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PasswordSU)
                    .addComponent(tfPasswordSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tfTempatLahirSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempatLahirSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTempatLahirSUActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    public void tambahAksi(ActionListener e) {
        btnLogin.addActionListener(e);
        btnRegister.addActionListener(e);
    }
    
    public Button getBtnLogin() {
        return btnLogin;
    }
    
    public Button getBtnRegister() {
        return btnRegister;
    }
    
    public String getUsername() {
        return tfUsername.getText();
    }
    
    public String getPassword() {
        return jPasswordField1.getText();
    }
    
    public String getNama() {
        return tfNamaSU.getText();
    }
    
    public String getNIm() {
        return tfNIMSU.getText();
    }
    
    public String getTempat() {
        return tfTempatLahirSU.getText();
    }
    
    public String getAlamat() {
        return jTextPane1.getText();
    }
    
    public String getUsernameReg() {
        return tfUsernameSU.getText();
    }
    
    public String getPasswordReg() {
        return tfPasswordSU.getText();
    }
    
    public int getTanggal() {
        return (tglHari.getSelectedIndex() + 1);
    }
    
    public String getBulan() {
        if (tglBulan.getSelectedIndex() == 0) {
            return "Januari";
        } else if (tglBulan.getSelectedIndex() == 1) {
            return "Februari";
        } else if (tglBulan.getSelectedIndex() == 2) {
            return "Maret";
        } else if (tglBulan.getSelectedIndex() == 3) {
            return "April";
        } else if (tglBulan.getSelectedIndex() == 4) {
            return "Mei";
        } else if (tglBulan.getSelectedIndex() == 5) {
            return "Juni";
        } else if (tglBulan.getSelectedIndex() == 6) {
            return "Juli";
        } else if (tglBulan.getSelectedIndex() == 7) {
            return "Agustus";
        } else if (tglBulan.getSelectedIndex() == 8) {
            return "September";
        } else if (tglBulan.getSelectedIndex() == 9) {
            return "Oktober";
        } else if (tglBulan.getSelectedIndex() == 10) {
            return "November";
        } else if (tglBulan.getSelectedIndex() == 11) {
            return "Desember";
        } else {
            return null;
        }
    }
    
    public int getTahun() {
        return 1990 + tglTahun.getSelectedIndex();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLogin;
    private java.awt.Button btnRegister;
    private javax.swing.JLabel headerSignUp;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbl_Alamat;
    private javax.swing.JLabel lbl_NIM;
    private javax.swing.JLabel lbl_Nama;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_PasswordSU;
    private javax.swing.JLabel lbl_TTL;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_UsernameSU;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelReg;
    private javax.swing.JTextField tfNIMSU;
    private javax.swing.JTextField tfNamaSU;
    private javax.swing.JTextField tfPasswordSU;
    private javax.swing.JTextField tfTempatLahirSU;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfUsernameSU;
    private javax.swing.JComboBox<String> tglBulan;
    private javax.swing.JComboBox<String> tglHari;
    private javax.swing.JComboBox<String> tglTahun;
    private javax.swing.JSeparator underlinePassword;
    private javax.swing.JSeparator underlineUsername;
    // End of variables declaration//GEN-END:variables
}
