/*
 * Tugas Besar - Pemrograman Berorientasi Objek
 * Muhammad Maulud H. R. | 1301154166
 * M. Widadio Ilham	  | 1301154360
 * Afra W. D.	  | 1301150432
 */
package viewOld;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author Muhammad Maulud H R
 */
public class MenuDosen extends javax.swing.JFrame {

    /**
     * Creates new form MenuDosen
     */
    public MenuDosen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCreate = new javax.swing.JMenu();
        createKelas = new javax.swing.JMenuItem();
        createTugas = new javax.swing.JMenuItem();
        menuUpdate = new javax.swing.JMenu();
        upDataTugas = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenu();
        deleteKelas = new javax.swing.JMenuItem();
        deleteTugas = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        viewKelas = new javax.swing.JMenuItem();
        viewTugas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome, ");

        lblUsername.setFont(new java.awt.Font("Myriad Pro", 0, 68)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblUsername))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        menuCreate.setText("Create");
        menuCreate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        createKelas.setText("Kelas");
        createKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createKelasActionPerformed(evt);
            }
        });
        menuCreate.add(createKelas);

        createTugas.setText("Tugas");
        menuCreate.add(createTugas);

        jMenuBar1.add(menuCreate);

        menuUpdate.setText("Update");
        menuUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        upDataTugas.setText("Update Data Tugas");
        menuUpdate.add(upDataTugas);

        jMenuBar1.add(menuUpdate);

        menuDelete.setText("Delete");
        menuDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        deleteKelas.setText("Kelas");
        menuDelete.add(deleteKelas);

        deleteTugas.setText("Tugas");
        menuDelete.add(deleteTugas);

        jMenuBar1.add(menuDelete);

        menuView.setText("View");
        menuView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        viewKelas.setText("Data Kelas");
        menuView.add(viewKelas);

        viewTugas.setText("Data Tugas");
        viewTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTugasActionPerformed(evt);
            }
        });
        menuView.add(viewTugas);

        jMenuBar1.add(menuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createKelasActionPerformed

    private void viewTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTugasActionPerformed

    public void setUsername(String s) {
        lblUsername.setText(s);
    }
    
    public void tambahAksi(ActionListener e) {
        createKelas.addActionListener(e);
        createTugas.addActionListener(e);
        deleteKelas.addActionListener(e);
        deleteTugas.addActionListener(e);
        upDataTugas.addActionListener(e);
        viewKelas.addActionListener(e);
        viewTugas.addActionListener(e);
    }
    
    public JMenuItem getCreateKelas() {
        return createKelas;
    }
    
    public JMenuItem getCreateTugas() {
        return createTugas;
    }
    
    public JMenuItem getDeleteKelas() {
        return deleteKelas;
    }
    
    public JMenuItem getDeleteTugas() {
        return deleteTugas;
    }
    
    public JMenuItem getUpDataTugas() {
        return upDataTugas;
    }
    
    public JMenuItem getViewKelas() {
        return viewKelas;
    }
    
    public JMenuItem getViewTugas() {
        return viewTugas;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createKelas;
    private javax.swing.JMenuItem createTugas;
    private javax.swing.JMenuItem deleteKelas;
    private javax.swing.JMenuItem deleteTugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu menuCreate;
    private javax.swing.JMenu menuDelete;
    private javax.swing.JMenu menuUpdate;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem upDataTugas;
    private javax.swing.JMenuItem viewKelas;
    private javax.swing.JMenuItem viewTugas;
    // End of variables declaration//GEN-END:variables
}
